workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: linux
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android APK (release)
        script: |
          flutter build apk --release
      - name: Build Android App Bundle (AAB)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
